# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${project.name}
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Settings related to the player join/quit event.
# -------------------------------------------------------------------------------------------------
Join_Quit_Events:

  # Sent when players have 'hub.event.joinmessage'/'hub.event.quitmessage' permission!
  # Support PlaceholderAPI.
  #
  # Built-in placeholders:
  # {player} - The player's displayname.
  # {username} - The player's username.
  # {prefix} - The player's prefix. Require Vault and permissions plugin (e.g. LuckPerms).
  # {suffix} - The player's suffix. Require Vault and permissions plugin (e.g. LuckPerms).
  # {plugin_prefix} - The plugin's prefix.
  Join_Message: '{plugin_prefix}{prefix}{player}{suffix} &6joined the lobby!'
  Quit_Message: ''

# -------------------------------------------------------------------------------------------------
# Hub/lobby protection
# -------------------------------------------------------------------------------------------------

Block_Break: false
Block_Interact: false
Block_Place: false
Block_Burn: false

Drowning_Damage: false
Fall_Damage: false
Fire_Damage: false

Fire_Spread: false
Leaves_Decay: false
Item_Drop: false
Item_Pickup: false
Hunger_Loss: false
Mob_Spawn: false
Weather_Change: false

# -------------------------------------------------------------------------------------------------
# Other flags
# -------------------------------------------------------------------------------------------------
Death_Messages: false

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? Use suffixes of files from localization/ folder.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages. You can manually use it with
# {plugin_prefix} variable anywhere.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&9${project.name}&8]&7 "

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: ${config.version}