# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${project.name}
# !-----------------------------------------------------------------------------------------------!

# Players with the 'hub.event.blockbreak' permission will bypass this setting.
Block_Break: false

# Players with the 'hub.event.blockplace' permission will bypass this setting.
Block_Place: false

Block_Burn: false
Fire_Spread: false

# Players with the 'hub.event.itemdrop' permission will bypass this setting.
Item_Drop: false

# Players with the 'hub.event.itempickup' permission will bypass this setting.
Item_Pickup: false

Hunger_Loss: false
Weather_Change: false
Death_Messages: false

# -------------------------------------------------------------------------------------------------
# Settings related to the player join/quit event.
# -------------------------------------------------------------------------------------------------
Join_Quit_Events:

  # Sent when players have 'hub.event.joinmessage'/'hub.event.quitmessage' permission!
  # Support PlaceholderAPI.
  #
  # Built-in placeholders:
  # {player} - The player's displayname.
  # {username} - The player's username.
  # {prefix} - The player's prefix. Require Vault and permissions plugin (e.g. LuckPerms).
  # {suffix} - The player's suffix. Require Vault and permissions plugin (e.g. LuckPerms).
  # {plugin_prefix} - The plugin's prefix.
  Join_Message: '{plugin_prefix}{prefix}{player}{suffix} &6joined the lobby!'
  Quit_Message: ''

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? Use suffixes of files from localization/ folder.
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages. You can manually use it with
# {plugin_prefix} variable anywhere.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&9${project.name}&8]&7 "

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 4